In [48]:
import pandas as pd
import numpy as np

# Reading training data

In [49]:
df = pd.read_csv(r"C:\Users\Saideep\Downloads\0000000000002329_training_diabetes_x_y_train.csv");
df.shape

(331, 11)

In [50]:
df.describe()

# age         sex         bmi          bp          s1          s2  \
count  331.000000  331.000000  331.000000  331.000000  331.000000  331.000000   
mean    -0.000214   -0.000293    0.000053   -0.001045   -0.001423   -0.001220   
std      0.047207    0.047618    0.048627    0.047621    0.047371    0.046936   
min     -0.107226   -0.044642   -0.090275   -0.102071   -0.126781   -0.115613   
25%     -0.034575   -0.044642   -0.035307   -0.036656   -0.035968   -0.029967   
50%      0.005383   -0.044642   -0.008362   -0.005671   -0.004321   -0.004445   
75%      0.038076    0.050680    0.030979    0.032775    0.027326    0.028905   
max      0.110727    0.050680    0.170555    0.132044    0.153914    0.198788   

               s3          s4          s5          s6           Y  
count  331.000000  331.000000  331.000000  331.000000  331.000000  
mean     0.000440   -0.001473   -0.001594    0.000099  149.722054  
std      0.047303    0.046591    0.048088    0.047263   76.796907  
min     -0.102307   -0.076395   -0.126097   -0.137767   25.000000  
25%     -0.032356   -0.039493   -0.035817   -0.034215   84.000000  
50%     -0.006584   -0.002592   -0.005145   -0.001078  138.000000  
75%      0.026550    0.034309    0.032124    0.027917  202.000000  
max      0.181179    0.185234    0.133599    0.135612  346.000000

In [51]:
X_train = np.array(df.iloc[:,0:10])
Y_train = np.array(df.iloc[:,10])
X_train,Y_train

(array([[-0.04910502, -0.04464164,  0.16085492, ...,  0.03430886,
          0.02801651,  0.01134862],
        [-0.07090025,  0.05068012, -0.08919748, ..., -0.00259226,
         -0.01290794, -0.05492509],
        [ 0.00175052, -0.04464164, -0.07087468, ..., -0.03949338,
         -0.02251217,  0.00720652],
        ...,
        [ 0.02354575, -0.04464164,  0.0703187 , ..., -0.00259226,
         -0.01919705, -0.00936191],
        [ 0.01628068,  0.05068012,  0.07247433, ..., -0.00259226,
         -0.02364456,  0.06105391],
        [-0.00914709,  0.05068012, -0.03099563, ..., -0.00259226,
          0.00620932,  0.02791705]]),
 array([346., 104.,  49., 180., 110.,  72.,  68., 216.,  47., 296.,  65.,
         96.,  67.,  52., 100., 202., 128.,  63., 281., 152., 124., 245.,
        101., 113.,  48., 197., 186., 132., 245.,  91.,  43., 101., 111.,
        199., 220., 281., 217.,  93., 174., 150., 206.,  61.,  55., 118.,
         53., 275., 215., 142.,  90.,  65., 200.,  96., 249., 200., 155.,
   

In [52]:
from sklearn.linear_model import LinearRegression 

In [53]:
algo = LinearRegression()

In [54]:
algo.fit(X_train,Y_train)
algo.coef_,algo.intercept_

(array([  21.73408096, -256.66866675,  569.60940087,  303.63233545,
        -833.11088526,  525.74313633,  136.07129167,  140.89458927,
         731.44498492,   53.32119133]),
 150.702574894566)

# Reading testing data

In [65]:
df = pd.read_csv(r"C:\Users\Saideep\Downloads\0000000000002329_test_diabetes_x_test.csv")
X_test = np.array(df.iloc[:,0:10])
X_test.shape

(110, 10)

In [70]:
Y_predict = algo.predict(X_test)
Y_predict_rounded = np.around(Y_predict, decimals=5)
Y_predict_rounded

array([105.80392, 178.60857,  79.38288,  52.95869,  98.87264, 150.71755,
        34.86515, 113.13536, 161.50184, 135.86156,  94.71592, 138.48094,
       141.37442, 158.76863, 171.65289, 106.44836, 103.9266 ,  95.38694,
       167.40118, 166.53426, 101.53465, 252.45036, 147.02259, 214.78907,
       161.27557, 210.61315,  71.78092, 189.65032, 206.61343, 219.98643,
       168.80193, 116.84846, 178.744  ,  77.03247,  59.54633, 111.56738,
       156.95187, 154.59591, 198.94457, 115.53884, 153.46699,  84.9618 ,
       113.70337, 142.14156, 147.3104 ,  82.78072,  77.89237, 128.99006,
       261.58712, 213.31188, 243.98791, 167.68132, 183.69712, 166.85927,
       202.1144 , 220.39236, 172.40288, 176.60898, 109.04657, 276.3779 ,
        90.99942, 289.37221, 119.56253,  75.45688, 180.78599, 146.62093,
       156.42382,  41.07904, 247.90645, 207.99121,  90.09641, 222.2417 ,
       189.86378, 182.26954, 164.39881, 190.27067, 105.44868, 199.86136,
       245.79639, 123.20281, 119.41032, 145.8662 , 

In [76]:
df = pd.DataFrame(Y_predict_rounded)
df.to_csv('Y_predict.csv',index = False)